# Generated by Django 5.1.7 on 2025-03-27 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='media/plants/'),
        ),
    ]
